AWSTemplateFormatVersion: "2010-09-09"
Description: Creating a s3 bucket.

Parameters:
  MyBucketName:
    Type: String
    Description: Enter the bucket name

Resources:

  # Creating a bucket.
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Ref: MyBucketName
